[build]
  command = "yarn netlify-export"
  publish = "out"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

  [plugins.inputs.thresholds]
    # TEMPORARY - bump back up to 0.72 once we get Netlify CMS running.
    performance = 0.66
    accessibility = 1
    best-practices = 0.93
    seo = 0.9

  [plugins.inputs]
    output_path = "lighthouse.html"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins]]
  package = "netlify-plugin-cache-nextjs"

[[plugins]]
  package = "netlify-plugin-image-optim"
