name: Lighthouse CI

on:
  push:
    branches: [main]
  pull_request:
    types: [labeled]

jobs:
  lhci:
    name: Run Lighthouse CI
    runs-on: ubuntu-latest

    if: ${{ !contains(github.event.pull_request.labels.*.names, 'need-perf-check') }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: "14"

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Wait for the Netlify Preview
        uses: jakepartusch/wait-for-netlify-action@v1
        id: netlify
        with:
          site_name: 'wargabantuwarga'

      - name: "Lighthouse CI (Preview)"
        id: lhci
        shell: bash
        run: |
          yarn global add @lhci/cli@0.8.x
          echo -e "\n"
          echo "Start collecting LH report..."
          lhci collect --url=${{ steps.netlify.outputs.url }} -n=1
          echo -e "\n"
          echo "Start asserting score..."
          lhci assert --config=./lighthouserc.js
          echo -e "\n"
          echo "Start uploading the report..."
          lhci upload --target "temporary-public-storage" --githubAppToken "$LHCI_GITHUB_APP_TOKEN"
        with:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
