on:
  pull_request_target:
    types: [opened, synchronize]

name: Lighthouse

jobs:
  install-deps:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "14"
      - run: yarn install --frozen-lockfile
      # Doesn't need to run this???
      # - run: yarn run fetch-wbw
      - uses: actions/cache@v1
        id: cache-deps
        with:
          path: "."
          key: ${{ github.sha }}

  lh-ci:
    name: Lighthouse CI
    runs-on: ubuntu-latest
    needs: install-deps
    steps:
      - uses: actions/cache@v1
        id: restore-deps
        with:
          path: "."
          key: ${{ github.sha }}
      - uses: actions/setup-node@v1
        with:
          node-version: "14"
      - name: Wait for the Netlify Preview
        uses: jakepartusch/wait-for-netlify-action@v1
        id: netlify
        with:
          site_name: 'wargabantuwarga'
      - name: "Lighthouse CI (Preview)"
        id: lhcli
        shell: bash
        run: |
          yarn global add @lhci/cli@0.8.x
          echo -e "\n"
          echo "Start collecting LH report..."
          lhci collect --url=${{ steps.netlify.outputs.url }} -n=1
          echo -e "\n"
          echo "Start asserting score..."
          lhci assert --config=./lighthouserc.js
          echo -e "\n"
          echo "Start uploading the report..."
          lhci upload --target "temporary-public-storage"

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body: |
            This is a multi-line test comment
            PR #${{ github.event.pull_request.number }}
            ${{join(steps.lhcli.outputs.*, '\n')}}
          reactions: '+1'
