on:
  pull_request:
    types: [opened, synchronize, reopened]

name: Lighthouse

jobs:
  lh-ci:
    name: Lighthouse CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: "14"
      - name: Wait for the Netlify Preview
        uses: jakepartusch/wait-for-netlify-action@v1
        id: netlify
        with:
          site_name: 'wargabantuwarga'
      - name: "Lighthouse CI (Preview)"
        id: lhcli
        shell: bash
        run: |
          yarn global add @lhci/cli@0.8.x
          echo -e "\n"
          echo "Start collecting LH report..."
          lhci collect --url=${{ steps.netlify.outputs.url }} -n=1
          echo -e "\n"
          echo "Start asserting score..."
          lhci assert --config=../lighthouserc.js
          echo -e "\n"
          echo "Start uploading the report..."
          lhci upload --target "temporary-public-storage"

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          # token: ${{ secrets.GITHUB_TOKEN }}
          token: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body: |
            Test by mazipan for #${{ github.event.pull_request.number }}
            ${{join(steps.lhcli.outputs.*, '\n')}}
          reactions: '+1'
