on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]

name: CI

jobs:
  install-deps:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "14"
      - run: yarn install --frozen-lockfile
      - run: yarn run fetch-wbw
      - uses: actions/cache@v1
        id: cache-deps
        with:
          path: "."
          key: ${{ github.sha }}

  lint:
    name: ESLint
    runs-on: ubuntu-latest
    needs: install-deps
    steps:
      - uses: actions/cache@v1
        id: restore-deps
        with:
          path: "."
          key: ${{ github.sha }}
      - uses: actions/setup-node@v1
        with:
          node-version: "14"
      - run: yarn run lint
        env:
          CI: true

  type-check:
    name: Type check
    runs-on: ubuntu-latest
    needs: install-deps
    steps:
      - uses: actions/cache@v1
        id: restore-deps
        with:
          path: "."
          key: ${{ github.sha }}
      - uses: actions/setup-node@v1
        with:
          node-version: "14"
      - run: yarn run type-check
        env:
          CI: true

  lh-ci:
    name: Lighthouse CI
    runs-on: ubuntu-latest
    needs: install-deps
    steps:
      - uses: actions/cache@v1
        id: restore-deps
        with:
          path: "."
          key: ${{ github.sha }}
      - uses: actions/setup-node@v1
        with:
          node-version: "14"
      - name: Wait for the Netlify Preview
        uses: jakepartusch/wait-for-netlify-action@v1
        id: netlify
        with:
          site_name: 'wargabantuwarga'
      - name: "Lighthouse CI for PR #${{ github.event.pull_request.number }} (Preview)"
        shell: bash
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
        run: |
          yarn global add @lhci/cli@0.8.x
          node ./.github/dummy.js
          echo ""
          echo "Start collecting LH report..."
          lhci collect --url=${{ steps.netlify.outputs.url }} -n=1
          echo ""
          echo "Start asserting score..."
          lhci assert --config=./lighthouserc.js
          echo ""
          echo "Start uploading the report..."
          echo "Check this: $LHCI_GITHUB_APP_TOKEN..."
          lhci upload --target "temporary-public-storage" --githubAppToken="$LHCI_GITHUB_APP_TOKEN"

