on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]

name: CI

jobs:
  install-deps:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "14"
      - run: yarn install --frozen-lockfile
      - run: yarn run fetch-wbw
      - uses: actions/cache@v1
        id: cache-deps
        with:
          path: "."
          key: ${{ github.sha }}

  lint:
    name: ESLint
    runs-on: ubuntu-latest
    needs: install-deps
    steps:
      - uses: actions/cache@v1
        id: restore-deps
        with:
          path: "."
          key: ${{ github.sha }}
      - uses: actions/setup-node@v1
        with:
          node-version: "14"
      - run: yarn run lint
        env:
          CI: true

  type-check:
    name: Type check
    runs-on: ubuntu-latest
    needs: install-deps
    steps:
      - uses: actions/cache@v1
        id: restore-deps
        with:
          path: "."
          key: ${{ github.sha }}
      - uses: actions/setup-node@v1
        with:
          node-version: "14"
      - run: yarn run type-check
        env:
          CI: true

  lh-ci:
    name: Lighthouse CI
    runs-on: ubuntu-latest
    needs: install-deps
    steps:
      - uses: actions/cache@v1
        id: restore-deps
        with:
          path: "."
          key: ${{ github.sha }}
      - uses: actions/setup-node@v1
        with:
          node-version: "14"
      # seems we don't need to build, the build process will handled by Netlify
      # - run: yarn run build
      - name: Wait for the Netlify Preview
        uses: jakepartusch/wait-for-netlify-action@v1
        id: netlify
        with:
          site_name: 'wargabantuwarga'
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v8
        with:
          urls: |
            ${{ steps.netlify.outputs.url }}
            ${{ steps.netlify.outputs.url }}/faq/
          budgetPath: ./budget.json
          uploadArtifacts: true
